Repository COS301-SE-2025/Visual-Compiler, pull requests merged in 2025-09, with the labels that each got.

#477 Pulling new optimiser endpoints into 'backend' branch
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/optimising.go
  visual-compiler/backend/api/handlers/projects.go
  visual-compiler/backend/api/routers/optimising-router.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/main.go
Labels: feature

#480 Feature/#467/optimizer
  .github/workflows/main.yml
  README.md
  codecov.yml
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/main.go
  visual-compiler/e2e-tests/e2e/analyser.cy.js
  visual-compiler/e2e-tests/e2e/canvas.cy.js
  visual-compiler/e2e-tests/e2e/lexer.cy.js
  visual-compiler/e2e-tests/e2e/parser.cy.js
  visual-compiler/e2e-tests/e2e/translator.cy.js
  visual-compiler/frontend/src/lib/components/analyser/analyser-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/main/Toolbox.svelte
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/stores/optimizer.ts
  visual-compiler/frontend/src/lib/types.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
  visual-compiler/frontend/unit-tests/analyser-phase-inspector-additional.test.ts
  visual-compiler/frontend/unit-tests/lexer-phase-inspector-enhanced.test.ts
  visual-compiler/frontend/vite.config.ts
  visual-compiler/package.json
Labels: feature

#481 Frontend
  README.md
  visual-compiler/e2e-tests/e2e/canvas.cy.js
  visual-compiler/frontend/src/lib/components/main/Toolbox.svelte
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/stores/optimizer.ts
  visual-compiler/frontend/src/lib/types.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: feature

#486 #483/feature/optimisation tutorial
  .github/workflows/main.yml
  docker-compose.yml
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/optimising.go
  visual-compiler/backend/api/handlers/projects.go
  visual-compiler/backend/api/routers/optimising-router.go
  visual-compiler/backend/api/unit-tests/optimising-router-unit_test.go
  visual-compiler/backend/api/unit-tests/optimising-unit_test.go
  visual-compiler/backend/core/services/optimiser.go
  visual-compiler/backend/core/unit-tests/optimiser-unit_test.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/main.go
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-tutorial.svelte
Labels: feature

#493 Frontend
  visual-compiler/frontend/src/lib/components/main/Toolbox.svelte
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-tutorial.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: enhancement

#511 Pulling 'optimiser' into 'main'
  docker-compose.yml
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/optimising.go
  visual-compiler/backend/api/handlers/projects.go
  visual-compiler/backend/api/routers/optimising-router.go
  visual-compiler/backend/api/unit-tests/optimising-router-unit_test.go
  visual-compiler/backend/api/unit-tests/optimising-unit_test.go
  visual-compiler/backend/core/services/optimiser.go
  visual-compiler/backend/core/unit-tests/optimiser-unit_test.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/main.go
  visual-compiler/frontend/src/lib/components/main/Toolbox.svelte
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/stores/optimizer.ts
  visual-compiler/frontend/src/lib/types.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
  visual-compiler/frontend/unit-tests/toolbox.test.ts
Labels: feature

#523 Integration/#506/external auth with frontend
  visual-compiler/backend/main.go
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
Labels: integration

#524 Feature/470/external authentication
  visual-compiler/backend/api/handlers/optimising.go
  visual-compiler/backend/api/routers/optimising-router.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/main.go
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
Labels: integration

#526 Dev: external auth integration
  .github/workflows/main.yml
  visual-compiler/backend/api/handlers/optimising.go
  visual-compiler/backend/api/routers/optimising-router.go
  visual-compiler/backend/core/services/optimiser.go
  visual-compiler/backend/core/unit-tests/optimiser-unit_test.go
  visual-compiler/backend/core/unit-tests/translator-unit_test.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/integration-tests/api-core-lexer-integration_test.go
  visual-compiler/backend/integration-tests/api-core-optimiser-integration_test.go
  visual-compiler/backend/integration-tests/api-core-parser-integration_test.go
  visual-compiler/backend/integration-tests/shared-functions_test.go
  visual-compiler/backend/main.go
  visual-compiler/cypress.config.js
  visual-compiler/e2e-tests/e2e/analyser.cy.js
  visual-compiler/e2e-tests/e2e/canvas.cy.js
  visual-compiler/e2e-tests/e2e/lexer.cy.js
  visual-compiler/e2e-tests/e2e/optimiser.cy.js
  visual-compiler/e2e-tests/e2e/parser.cy.js
  visual-compiler/e2e-tests/e2e/register.cy.js
  visual-compiler/e2e-tests/e2e/translator.cy.js
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/optimizer/optimizer-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
  visual-compiler/frontend/unit-tests/toolbox.test.ts
Labels: integration

#528 Pulling dev with external auth to 'backend'
  visual-compiler/backend/api/handlers/analysing.go
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/handlers/login.go
  visual-compiler/backend/api/handlers/parsing.go
  visual-compiler/backend/api/handlers/register.go
  visual-compiler/backend/api/handlers/translator.go
  visual-compiler/backend/api/routers/analysing-router.go
  visual-compiler/backend/api/routers/lexing-router.go
  visual-compiler/backend/api/routers/middleware.go
  visual-compiler/backend/api/routers/parsing-router.go
  visual-compiler/backend/api/routers/translator-router.go
  visual-compiler/backend/go.mod
  visual-compiler/backend/go.sum
  visual-compiler/backend/main.go
Labels: fixes

#532 Pulling ai core functionality to feature branch
  visual-compiler/backend/core/ai/assistant.go
  visual-compiler/backend/go.mod
  visual-compiler/backend/go.sum
Labels: feature

#540 Feature/#497/ai chatbot component
  visual-compiler/frontend/src/lib/components/main/ai-assistant.svelte
  visual-compiler/frontend/src/lib/stores/pipeline.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: feature

#541 Dev
  visual-compiler/backend/api/handlers/ai-functions.go
  visual-compiler/backend/api/handlers/analysing.go
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/handlers/optimising.go
  visual-compiler/backend/api/handlers/parsing.go
  visual-compiler/backend/api/handlers/translator.go
  visual-compiler/backend/api/routers/ai-endpoints.go
  visual-compiler/backend/api/routers/lexing-router.go
  visual-compiler/backend/api/routers/parsing-router.go
  visual-compiler/backend/core/ai/assistant.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/go.mod
  visual-compiler/backend/go.sum
  visual-compiler/backend/main.go
Labels: integration

#588 Dev
  visual-compiler/backend/core/ai/assistant.go
  visual-compiler/frontend/src/lib/components/main/ai-assistant.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
Labels: fixes

#609 Hotfix/#536/adding node shoudnt reset edges
  .github/workflows/main.yml
  visual-compiler/backend/api/routers/middleware.go
  visual-compiler/backend/core/ai/assistant.go
  visual-compiler/backend/core/services/analyser.go
  visual-compiler/backend/core/services/parser.go
  visual-compiler/backend/core/unit-tests/analyser-unit_test.go
  visual-compiler/backend/core/unit-tests/parser-unit_test.go
  visual-compiler/e2e-tests/e2e/analyser.cy.js
  visual-compiler/e2e-tests/e2e/canvas.cy.js
  visual-compiler/e2e-tests/e2e/lexer.cy.js
  visual-compiler/e2e-tests/e2e/optimiser.cy.js
  visual-compiler/e2e-tests/e2e/parser.cy.js
  visual-compiler/e2e-tests/e2e/translator.cy.js
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/canvas-tutorial.svelte
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/src/lib/components/main/tutorial.svelte
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
  visual-compiler/quality-tests/performance-tests/analyser-test.js
  visual-compiler/quality-tests/performance-tests/guest-login-test.js
  visual-compiler/quality-tests/performance-tests/lexer-test.js
  visual-compiler/quality-tests/performance-tests/login-test.js
  visual-compiler/quality-tests/performance-tests/optimiser-test.js
  visual-compiler/quality-tests/performance-tests/parser-test.js
  visual-compiler/quality-tests/performance-tests/register-test.js
  visual-compiler/quality-tests/performance-tests/source-code-test.js
  visual-compiler/quality-tests/performance-tests/translator-test.js
  visual-compiler/quality-tests/tests.md
Labels: bug

#610 #enhancement/added recentre button + source code component enhancement
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: enhancement

#615 fix/AI - Parsing input layout
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
Labels: integration

#618 Enhancement/#616/change default input to show example
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/optimiser/optimiser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
Labels: enhancement

#620 #619/enhancement/changed parsing component
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
Labels: enhancement

#624 #623/enhancement/added scroll animation
  visual-compiler/frontend/src/lib/components/landing/Hero.svelte
Labels: enhancement

#625 Hotfix/input management
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/lexer/lexer-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/clear-canvas-confirmation.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/lib/stores/lexer.ts
  visual-compiler/frontend/src/lib/stores/parser.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: fixes

#635 hotfix/#634/AI icone, scrollbar and go to bottom when a message is se…
  visual-compiler/frontend/src/lib/components/main/ai-assistant.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
Labels: fixes

#645 Hotfix/#642/source code and lexer display
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/clear-canvas-confirmation.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/project-hub/project-hub.svelte
  visual-compiler/frontend/src/lib/stores/parser.ts
  visual-compiler/frontend/src/lib/stores/project.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: fixes

#648 Hotfix/#643/dark mode adjustments
  visual-compiler/frontend/src/lib/components/analyser/analyser-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/lexer/lexer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/ai-assistant.svelte
  visual-compiler/frontend/src/lib/components/main/clear-canvas-confirmation.svelte
  visual-compiler/frontend/src/lib/components/optimiser/optimiser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/parser/parser-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/project-hub/delete-confirmation.svelte
  visual-compiler/frontend/src/lib/components/project-hub/project-hub.svelte
  visual-compiler/frontend/src/lib/components/project-hub/project-name-prompt.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-tutorial.svelte
Labels: fixes

#651 Hotfix/#632/fix unit tests
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/unit-tests/analyser-phase-inspector-additional.test.ts
  visual-compiler/frontend/unit-tests/analyser-phase-inspector-coverage.test.ts
  visual-compiler/frontend/unit-tests/analyser-phase-inspector-enhanced.test.ts
  visual-compiler/frontend/unit-tests/analyser-phase-inspector.test.ts
  visual-compiler/frontend/unit-tests/auth-page.test.ts
  visual-compiler/frontend/unit-tests/code-input.test.ts
  visual-compiler/frontend/unit-tests/help-menu.test.ts
  visual-compiler/frontend/unit-tests/lexer-phase-inspector-enhanced.test.ts
  visual-compiler/frontend/unit-tests/lexer-phase-inspector.test.ts
  visual-compiler/frontend/unit-tests/lexer-phase-tutorial.test.ts
  visual-compiler/frontend/unit-tests/lexor-artifact-viewer.test.ts
  visual-compiler/frontend/unit-tests/nav-bar.test.ts
  visual-compiler/frontend/unit-tests/optimiser-artifact-viewer.test.ts
  visual-compiler/frontend/unit-tests/optimiser-phase-inspector.test.ts
  visual-compiler/frontend/unit-tests/parsing-input.test.ts
  visual-compiler/frontend/unit-tests/phase-inspector.test.ts
  visual-compiler/frontend/unit-tests/project-hub.test.ts
  visual-compiler/frontend/unit-tests/theme-store.test.ts
  visual-compiler/frontend/unit-tests/translator-phase-inspector.test.ts
Labels: testing
