Repository COS301-SE-2025/Visual-Compiler, pull requests merged in 2025-08, with the labels that each got.

#300 #299/integration/Translator artifact integrated
  visual-compiler/frontend/src/lib/components/translator/translator-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: integration

#313 #241/nfa+dfa full screen vizualizations
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
Labels: enhancement

#315 #247/enhancement/added syntax tree full screen functionality
  visual-compiler/frontend/src/lib/components/parser/parser-artifact-viewer.svelte
Labels: enhancement

#321 Enhancement/#316/enhancement translator error feedback
  visual-compiler/frontend/src/lib/components/translator/translator-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: enhancement

#323 #301/full translator tutorial features and content
  visual-compiler/frontend/src/lib/components/translator/translator-phase-tutorial.svelte
Labels: feature

#331 integration
  visual-compiler/backend/api/handlers/analysing.go
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/handlers/login.go
  visual-compiler/backend/api/handlers/parsing.go
  visual-compiler/backend/api/handlers/projects.go
  visual-compiler/backend/api/handlers/register.go
  visual-compiler/backend/api/handlers/translator.go
  visual-compiler/backend/api/handlers/users.go
  visual-compiler/backend/api/routers/user-routers.go
  visual-compiler/backend/core/services/lexer.go
  visual-compiler/backend/core/services/parser.go
  visual-compiler/backend/core/services/translator.go
  visual-compiler/backend/core/unit-tests/lexer-unit_test.go
  visual-compiler/backend/core/unit-tests/parser-unit_test.go
  visual-compiler/backend/core/unit-tests/translator-unit_test.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
Labels: integration

#334 Enhancement/#327/node functionality ajustment
  visual-compiler/frontend/src/lib/components/main/Toolbox.svelte
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/tests/unit-tests/toolbox.test.ts
Labels: enhancement

#341 #328/feature/added dropdown input
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
Labels: feature

#348 #346/ styling/ changes to light and dark mode to all componets
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/lexer/lexer-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/Toolbox.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/src/lib/components/parser/parser-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-tutorial.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: styling

#349 Pulling edit user endpoint into 'backend'
  visual-compiler/backend/api/handlers/users.go
  visual-compiler/backend/api/routers/user-routers.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
Labels: feature

#350 Frontend
  visual-compiler/backend/api/handlers/analysing.go
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/users.go
  visual-compiler/backend/core/services/analyser.go
  visual-compiler/backend/core/unit-tests/analyser-unit_test.go
  visual-compiler/backend/go.mod
  visual-compiler/backend/go.sum
  visual-compiler/frontend/src/lib/components/analyser/analyser-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/lexer/lexer-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/Toolbox.svelte
  visual-compiler/frontend/src/lib/components/main/admin-panel.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/src/lib/components/main/nav-bar.svelte
  visual-compiler/frontend/src/lib/components/parser/parser-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/parser/parser-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/project-hub/delete-confirmation.svelte
  visual-compiler/frontend/src/lib/components/project-hub/project-hub.svelte
  visual-compiler/frontend/src/lib/components/project-hub/project-name-prompt.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/stores/project.ts
  visual-compiler/frontend/src/lib/types.ts
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
  visual-compiler/frontend/tests/unit-tests/toolbox.test.ts
Labels: enhancement, styling, fixes

#351 Pulling 'backend' into 'dev'
  visual-compiler/backend/api/handlers/users.go
  visual-compiler/backend/api/routers/user-routers.go
  visual-compiler/backend/core/services/lexer.go
  visual-compiler/backend/core/unit-tests/lexer-unit_test.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
Labels: enhancement, feature

#367 Enhancement/#325/add zoom functionality
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/parser/parser-artifact-viewer.svelte
Labels: feature

#379 #368/feature/added textbox for instructions
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
Labels: feature

#380 #369/enhancement/updated toast notifacations
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/Toolbox.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/translator/translator-phase-inspector.svelte
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: enhancement

#382 Integration/#381/project source code input
  README.md
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: integration

#383 Testing/#375/add unit tests for new components
  README.md
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
  visual-compiler/frontend/tests/unit-tests/admin-panel.test.ts
  visual-compiler/frontend/tests/unit-tests/analyser-artifact-viewer.test.ts
  visual-compiler/frontend/tests/unit-tests/analyser-phase-inspector.test.ts
  visual-compiler/frontend/tests/unit-tests/analyser-phase-tutorial.test.ts
  visual-compiler/frontend/tests/unit-tests/auth-page.test.ts
  visual-compiler/frontend/tests/unit-tests/code-input.test.ts
  visual-compiler/frontend/tests/unit-tests/delete-confirmation.test.ts
  visual-compiler/frontend/tests/unit-tests/features.test.ts
  visual-compiler/frontend/tests/unit-tests/help-menu.test.ts
  visual-compiler/frontend/tests/unit-tests/lexer-phase-tutorial.test.ts
  visual-compiler/frontend/tests/unit-tests/loader-animation.test.ts
  visual-compiler/frontend/tests/unit-tests/parser-phase-tutorial.test.ts
  visual-compiler/frontend/tests/unit-tests/parsing-input.test.ts
  visual-compiler/frontend/tests/unit-tests/phase-inspector.test.ts
  visual-compiler/frontend/tests/unit-tests/project-hub.test.ts
  visual-compiler/frontend/tests/unit-tests/project-name-prompt.test.ts
  visual-compiler/frontend/tests/unit-tests/toast-container.test.ts
  visual-compiler/frontend/tests/unit-tests/translator-artifact-viewer.test.ts
  visual-compiler/frontend/tests/unit-tests/translator-phase-inspector.test.ts
  visual-compiler/frontend/tests/unit-tests/translator-phase-tutorial.test.ts
  visual-compiler/frontend/tests/unit-tests/walkthrough.test.ts
  visual-compiler/frontend/vitest-setup-client.ts
Labels: testing

#398 Pulling 'backend' into 'dev' part i dont know
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/projects.go
Labels: feature

#402 Frontend
  visual-compiler/frontend/src/lib/components/analyser/analyser-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/project-hub/project-hub.svelte
  visual-compiler/frontend/src/lib/stores/pipeline.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
  visual-compiler/frontend/tests/unit-tests/analyser-phase-inspector.test.ts
  visual-compiler/frontend/tests/unit-tests/drawer-canvas.test.ts
  visual-compiler/frontend/tests/unit-tests/landing-page.test.ts
  visual-compiler/frontend/tests/unit-tests/main-workspace.test.ts
  visual-compiler/frontend/tests/unit-tests/parsing-input.test.ts
  visual-compiler/frontend/tests/unit-tests/phase-inspector.test.ts
  visual-compiler/frontend/vitest-setup-client.ts
Labels: integration

#405 Frontend
  visual-compiler/frontend/src/lib/components/main/drawer-canvas.svelte
  visual-compiler/frontend/src/lib/components/project-hub/project-hub.svelte
  visual-compiler/frontend/src/lib/stores/pipeline.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: integration

#441 #432/hotfix/added path to allowed methods
  visual-compiler/backend/integration-tests/api-core-lexer-integration_test.go
  visual-compiler/backend/integration-tests/api-mongoDB-users-integration_test.go
  visual-compiler/backend/main.go
  visual-compiler/frontend/src/lib/components/main/admin-panel.svelte
Labels: bug

#444 Pulling new CI cypress into 'dev'
  .github/workflows/main.yml
  visual-compiler/backend/main.go
Labels: testing

#446 Integration/#412/saving all input and artifacts when loaded
  visual-compiler/frontend/src/lib/components/lexer/lexer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/project-hub/project-hub.svelte
  visual-compiler/frontend/src/lib/stores/lexer.ts
  visual-compiler/frontend/src/lib/stores/pipeline.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: integration

#447 Testing/#433/unit test coverage
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
  visual-compiler/frontend/unit-tests/analyser-phase-inspector-additional.test.ts
  visual-compiler/frontend/unit-tests/analyser-phase-inspector-enhanced.test.ts
  visual-compiler/frontend/unit-tests/clear-canvas-confirmation.test.ts
  visual-compiler/frontend/unit-tests/features.test.ts
  visual-compiler/frontend/unit-tests/hero.test.ts
  visual-compiler/frontend/unit-tests/index.test.ts
  visual-compiler/frontend/unit-tests/info-section.test.ts
  visual-compiler/frontend/unit-tests/landing-page.test.ts
  visual-compiler/frontend/unit-tests/layout.test.ts
  visual-compiler/frontend/unit-tests/lexer-phase-inspector-enhanced.test.ts
  visual-compiler/frontend/unit-tests/loader-animation.test.ts
  visual-compiler/frontend/unit-tests/main-workspace-coverage-enhancement.test.ts
  visual-compiler/frontend/unit-tests/main-workspace.test.ts
  visual-compiler/frontend/unit-tests/page-server.test.ts
  visual-compiler/frontend/unit-tests/pipeline-store.test.ts
  visual-compiler/frontend/unit-tests/project-hub.test.ts
  visual-compiler/frontend/unit-tests/project-store.test.ts
  visual-compiler/frontend/unit-tests/theme-store.test.ts
  visual-compiler/frontend/unit-tests/walkthrough.test.ts
  visual-compiler/frontend/vite.config.ts
Labels: testing
