Repository COS301-SE-2025/Visual-Compiler, pull requests merged in 2025-07, with the labels that each got.

#254 Pulling new code into 'backend'
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/handlers/login.go
  visual-compiler/backend/api/handlers/parsing.go
  visual-compiler/backend/api/handlers/register.go
  visual-compiler/backend/api/handlers/users.go
  visual-compiler/backend/core/services/parser.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/go.mod
  visual-compiler/backend/go.sum
  visual-compiler/backend/main.go
Labels: feature

#255 Pulling 'backend' into 'dev'
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/handlers/login.go
  visual-compiler/backend/api/handlers/parsing.go
  visual-compiler/backend/api/handlers/register.go
  visual-compiler/backend/api/handlers/users.go
  visual-compiler/backend/core/services/parser.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/go.mod
  visual-compiler/backend/go.sum
  visual-compiler/backend/main.go
Labels: feature

#262 #243/enhancement/source code state feedback
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/stores/sourceCode.ts
Labels: enhancement

#266 Pulling new endpoints into 'backend'
  visual-compiler/backend/api/handlers/analysing.go
  visual-compiler/backend/api/routers/analysing-router.go
  visual-compiler/backend/api/routers/lexing-router.go
  visual-compiler/backend/api/routers/parsing-router.go
  visual-compiler/backend/api/routers/user-routers.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/main.go
Labels: feature

#275 Enhancement/#239/dark mode styling update
  visual-compiler/frontend/src/lib/components/analyser/analyser-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/lexer/lexer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/lexer/lexer-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/admin-panel.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/lib/components/main/nav-bar.svelte
  visual-compiler/frontend/src/lib/components/parser/parser-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/stores/source-code.ts
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
  visual-compiler/frontend/src/routes/landing-page/+page.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
  visual-compiler/frontend/tests/unit-tests/hero.test.ts
  visual-compiler/frontend/tests/unit-tests/toolbox.test.ts
Labels: enhancement

#277 merge dev into front end
  visual-compiler/backend/api/handlers/analysing.go
  visual-compiler/backend/api/routers/analysing-router.go
  visual-compiler/backend/api/routers/lexing-router.go
  visual-compiler/backend/api/routers/parsing-router.go
  visual-compiler/backend/api/routers/user-routers.go
  visual-compiler/backend/core/services/analyser.go
  visual-compiler/backend/core/unit-tests/analyser-unit_test.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/main.go
Labels: integration

#279 Feature/#278/updated analyser input
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/admin-panel.svelte
Labels: feature

#280 Updated analyser input
  visual-compiler/frontend/src/lib/components/analyser/analyser-phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/admin-panel.svelte
Labels: feature

#287 Pulling translator endpoints into 'backend'
  visual-compiler/backend/api/handlers/translator.go
  visual-compiler/backend/api/routers/translator-router.go
  visual-compiler/backend/core/unit-tests/translator-unit_test.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/main.go
Labels: feature

#292 Dev
  visual-compiler/backend/api/handlers/analysing.go
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/translator.go
  visual-compiler/backend/api/handlers/users.go
  visual-compiler/backend/api/routers/translator-router.go
  visual-compiler/backend/core/services/parser.go
  visual-compiler/backend/core/services/translator.go
  visual-compiler/backend/core/unit-tests/translator-unit_test.go
  visual-compiler/backend/docs/docs.go
  visual-compiler/backend/docs/swagger.json
  visual-compiler/backend/docs/swagger.yaml
  visual-compiler/backend/main.go
Labels: integration
