Repository COS301-SE-2025/Visual-Compiler, pull requests merged in 2025-06, with the labels that each got.

#110 #109/feature/testing coverage
  .github/workflows/main.yml
Labels: feature

#148 #148/enhancement/fixed user id storage and retrieval
  .gitignore
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/handlers/login.go
Labels: enhancement

#154 #154/enhancement/added core md file with descriptions added
  visual-compiler/backend/core/core.md
  visual-compiler/backend/core/services/lexer.go
  visual-compiler/backend/tests/unit-tests/core-lexing-unit_test.go
Labels: feature

#157 #157/enhancement/lexer functions all updated
  visual-compiler/backend/core/core.md
  visual-compiler/backend/core/services/lexer.go
Labels: feature

#158 #158/feature/endpoints for lexing done (hopefully)
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/routers/lexing-router.go
  visual-compiler/backend/core/core.md
  visual-compiler/backend/core/services/lexer.go
  visual-compiler/backend/tests/unit-tests/core-lexing-unit_test.go
Labels: feature

#179 #104/automata re converter
  visual-compiler/frontend/src/lib/components/lexer/lexer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
Labels: enhancement, feature

#180 Frontend to dev
  visual-compiler/frontend/src/lib/components/lexer/lexer-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/routes/auth-page/+page.svelte
Labels: enhancement, integration, feature

#182 #182/feature/pull new endpoints into dev
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/routers/lexing-router.go
Labels: feature

#191 #126/feature/parsing-input
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
Labels: feature

#200 Feature/#172 feature lexing tutorial changes automatas
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/main/code-input.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: feature

#204 Backend
  visual-compiler/backend/api/handlers/parsing.go
  visual-compiler/backend/api/routers/parsing-router.go
  visual-compiler/backend/api/unit-tests/delete-user-unit_test.go
  visual-compiler/backend/api/unit-tests/lexing-routers-unit_test.go
  visual-compiler/backend/api/unit-tests/lexing-unit_test.go
  visual-compiler/backend/api/unit-tests/login-unit_test.go
  visual-compiler/backend/api/unit-tests/parsing-router-unit_test.go
  visual-compiler/backend/api/unit-tests/register-unit_test.go
  visual-compiler/backend/api/unit-tests/users-routers-unit_test.go
  visual-compiler/backend/core/core.md
  visual-compiler/backend/core/services/parser.go
  visual-compiler/backend/core/unit-tests/lexer-unit_test.go
  visual-compiler/backend/core/unit-tests/parser-unit_test.go
  visual-compiler/backend/integration-tests/api-core-integration_test.go
  visual-compiler/backend/integration-tests/api-mongoDB-integration_test.go
  visual-compiler/backend/integration-tests/tests.md
  visual-compiler/backend/tests/integration-tests/api-core-integration_test.go
  visual-compiler/backend/tests/tests.md
  visual-compiler/backend/tests/unit-tests/api-users-unit_test.go
  visual-compiler/frontend/eslint.config.js
  visual-compiler/frontend/package.json
Labels: feature

#205 #192/feature/faq-help-menu
  visual-compiler/frontend/src/lib/components/main/help-menu.svelte
  visual-compiler/frontend/src/lib/components/main/nav-bar.svelte
Labels: feature

#210 Backend
  visual-compiler/backend/api/handlers/parsing.go
  visual-compiler/backend/api/unit-tests/lexing-unit_test.go
  visual-compiler/backend/api/unit-tests/parsing-unit_test.go
  visual-compiler/backend/core/core.md
  visual-compiler/backend/core/services/parser.go
  visual-compiler/backend/core/unit-tests/parser-unit_test.go
  visual-compiler/backend/integration-tests/api-core-lexer-integration_test.go
  visual-compiler/backend/integration-tests/api-core-parser-integration_test.go
  visual-compiler/backend/integration-tests/tests.md
Labels: feature

#214 #195/styling/updated dark mode styles
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
Labels: styling

#215 Dev
  .github/workflows/main.yml
  README.md
  visual-compiler/backend/.env
  visual-compiler/backend/api/handlers/delete-user.go
  visual-compiler/backend/api/handlers/lexing.go
  visual-compiler/backend/api/handlers/login.go
  visual-compiler/backend/api/handlers/parsing.go
  visual-compiler/backend/api/handlers/register.go
  visual-compiler/backend/api/handlers/users.go
  visual-compiler/backend/api/routers/parsing-router.go
  visual-compiler/backend/api/unit-tests/delete-user-unit_test.go
  visual-compiler/backend/api/unit-tests/lexing-routers-unit_test.go
  visual-compiler/backend/api/unit-tests/lexing-unit_test.go
  visual-compiler/backend/api/unit-tests/login-unit_test.go
  visual-compiler/backend/api/unit-tests/parsing-router-unit_test.go
  visual-compiler/backend/api/unit-tests/parsing-unit_test.go
  visual-compiler/backend/api/unit-tests/register-unit_test.go
  visual-compiler/backend/api/unit-tests/users-routers-unit_test.go
  visual-compiler/backend/core/core.md
  visual-compiler/backend/core/db/mongo.go
  visual-compiler/backend/core/services/lexer.go
  visual-compiler/backend/core/services/parser.go
  visual-compiler/backend/core/unit-tests/lexer-unit_test.go
  visual-compiler/backend/core/unit-tests/parser-unit_test.go
  visual-compiler/backend/integration-tests/api-core-lexer-integration_test.go
  visual-compiler/backend/integration-tests/api-core-parser-integration_test.go
  visual-compiler/backend/integration-tests/api-mongoDB-integration_test.go
  visual-compiler/backend/integration-tests/tests.md
  visual-compiler/backend/main.go
  visual-compiler/backend/semgrep-go.yml
  visual-compiler/backend/tests/integration-tests/api-core-integration_test.go
  visual-compiler/backend/tests/tests.md
  visual-compiler/backend/tests/unit-tests/api-users-unit_test.go
  visual-compiler/frontend/eslint.config.js
  visual-compiler/frontend/package-lock.json
  visual-compiler/frontend/package.json
Labels: link

#221 #219/feature/default values for grammar
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
Labels: feature

#226 #103/feature/parsing artifacts
  visual-compiler/frontend/src/lib/components/parser/parser-artifact-viewer.svelte
  visual-compiler/frontend/src/lib/components/parser/parser-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/parser/parsing-input.svelte
  visual-compiler/frontend/src/lib/types.ts
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: feature

#229 #223/enhancement/modify mongo singleton and modified CI pipeline
  .github/workflows/main.yml
  .gitignore
  docker-compose.yml
  visual-compiler/backend/.dockerignore
  visual-compiler/backend/core/db/mongo.go
Labels: feature

#232 Feature/#102 feature parsing,lexing tutorial
  visual-compiler/backend/.env
  visual-compiler/frontend/src/lib/components/lexer/lexer-phase-tutorial.svelte
  visual-compiler/frontend/src/lib/components/lexer/phase-inspector.svelte
  visual-compiler/frontend/src/lib/components/parser/parser-phase-tutorial.svelte
  visual-compiler/frontend/src/routes/main-workspace/+page.svelte
Labels: enhancement, feature

#233 Backend
  .github/workflows/main.yml
  .gitignore
  docker-compose.yml
  visual-compiler/backend/.dockerignore
  visual-compiler/backend/core/db/mongo.go
Labels: feature
